### PR TITLE
Added 150kGT.

### PR DESCRIPTION
**Pull request by PinkPingPenguin**
Added 150K GT:
- Some are from 126k upgraded to reflect 150k (all cards quad) : The middle block
- Rest from real 150k+ players, mainly payers.

Feel free to add it to your work if it satisfies you ! =)

PinkPingPenguin.

PS : Thanks again for TU_Optimizer.

### CODE REVIEW

**Comment by zachanassian** [comment]
Thx. Will be added in next release. One question: Why: GT1SOkxxx and not GT150kxxx?

**Comment by PinkPingPenguin** [comment]
Thanks !

Uh 2 main reasons : 
- You've done the same for 100k and 125k
- I was not sure if it could create issues with the +GT150k: /^GT1SOk\d\d\d$/ so I prefered to make sure the 2 expressions were different.

**Comment by zachanassian** [comment]
Oh never realized this for GT1OO. Will fix this as well with next release.

**Comment by zachanassian** [comment]
I get warning messages for decks

<pre>
Warning while resolving Custom Deck #236 "GT150k002"
Warning while resolving Custom Deck #240 "GT150k006":
Warning while resolving Custom Deck #254 "GT150k020":
Warning while resolving Custom Deck #258 "GT150k024":
Warning while resolving Custom Deck #261 "GT150k027":
Warning while resolving Custom Deck #291 "GT150k057":
Warning while resolving Custom Deck #298 "GT150k064":
Warning while resolving Custom Deck #300 "GT150k066":
Warning while resolving Custom Deck #302 "GT150k068":
Warning while resolving Custom Deck #305 "GT150k071":
Warning while resolving Custom Deck #306 "GT150k072":
Warning while resolving Custom Deck #308 "GT150k074":
Warning while resolving Custom Deck #312 "GT150k078":
Warning while resolving Custom Deck #314 "GT150k080":
Warning while resolving Custom Deck #332 "GT150k098":
Warning while resolving Custom Deck #332 "GT150k098":
Warning while resolving Custom Deck #342 "GT150k108":
Warning while resolving Custom Deck #354 "GT150k120":
Warning while resolving Custom Deck #368 "GT150k134":
Warning while resolving Custom Deck #371 "GT150k137":
Warning while resolving Custom Deck #375 "GT150k141":
</pre>

some typing errors, some decks end with , so not clear if they are complete. Could you please fix and push again.

**Comment by zachanassian** [comment]
Seems there is no update. Feel free to request a new pull

**Pull request closed without merging**
